version: "3.9"

services:

  server:
    container_name: crud_rest_auth_server
    build: .
    ports:
      - "2525:2525"
    links:
      - database
    environment:
      MONGO_DB_HOST: database
      MONGO_DB_PORT: 27017
      MONGO_DB_NAME: crud-rest-auth

  database:
    container_name: crud_rest_auth_db
    image: mongo
    ports:
      - "27017:27017"
